# Generated by Django 6.0.7 on 2026-07-13 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0001_initial'),
        ('records', '0002_alter_cashflowrecord_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashflowrecord',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='directories.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='cashflowrecord',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='directories.subcategory', verbose_name='Подкатегория'),
        ),
    ]
